WeProvide\TranslationBundle\Entity\Translation:
#    type: mappedSuperclass






    type: entity
    repositoryClass: WeProvide\TranslationBundle\Repository\TranslationRepository

    table: we_provide_translation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

#    fields:
#        route_name:
#            type: string
#            length: 255
#        route_path:
#            type: string
#            length: 255
#        state:
#            type: boolean
