services:
    we_provide_admin_translation:
        class: WeProvide\TranslationBundle\Admin\TranslationAdmin
        arguments: [~, ~, WeProvideTranslationBundle:TranslationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Translation, label: Translation }
        public: true
