services:
    we_provide_translation_repository:
        class: WeProvide\TranslationBundle\Repository\TranslationRepository
        arguments: ['@file_locator', '@jms_translation.loader_manager', '%we_provide_translation.config%']

    we_provide_admin_translation:
        class: WeProvide\TranslationBundle\Admin\TranslationAdmin
        arguments: [~, ~, WeProvideTranslationBundle:TranslationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Translation, label: Translation }
        public: true
#        calls:
#            - [ setTranslationDomain, [WeProvideTranslationBundle]]  # For translations of our interface & messages
