services:
    we_provide_translation_repository:
        class: WeProvide\TranslationBundle\Repository\TranslationRepository
        arguments: ['@event_dispatcher', '@file_locator', '@jms_translation.loader_manager', '%we_provide_translation.config%']

    we_provide_admin_translation:
        class: WeProvide\TranslationBundle\Admin\TranslationAdmin
        arguments: [~, ~, WeProvideTranslationBundle:TranslationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Translation, label: Translation, label_catalogue: "WeProvideTranslationBundle" }
        public: true
        calls:
            - [ setTranslationDomain, [WeProvideTranslationBundle]]

    we_provide_translation_update_listener:
        class: WeProvide\TranslationBundle\Event\TranslationUpdateListener
        arguments: ['%kernel.cache_dir%']
        tags:
            - { name: kernel.event_listener, event: translation.update, method: onTranslationUpdate }